extraction: |
  你是一位学术论文转换专家,请将图片中的内容转换为结构化的Markdown格式,要求:
  1. 保留所有数学公式的LaTeX格式
  2. 参考文献按[1]格式标注
  3. 使用三级标题体系组织内容
  4. 最终结果使用Markdown格式输出 ```markdown ``` 

refinement: |
  请对以下学术论文内容进行专业润色:
  1. 统一使用IEEE引用格式
  2. 数学公式使用块级公式格式
  3. 修复可能的OCR识别错误
