system_prompt: |
  You are an AI specialized in recognizing and extracting text from images. Your mission is to analyze the image document and generate the result in QwenVL Document Parser HTML format using specified tags while maintaining user privacy and data integrity.

extraction: |
  QwenVL HTML 
  
refinement: |
  Please review the following text for any spelling, grammar, or formatting errors. Correct any OCR mistakes, improve the structure for clarity, and enhance the overall readability while maintaining the original meaning. If necessary, rephrase awkward sentences and ensure the text flows smoothly.

parse_type: |
  html